"""settings, board columns, girocode fields

Revision ID: 1252833500ab
Revises: 50370c6cad4b
Create Date: 2026-08-11 16:09:31.578565

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '1252833500ab'
down_revision: Union[str, None] = '50370c6cad4b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('app_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('admin_password_hash', sa.String(), nullable=True),
    sa.Column('imap_host', sa.String(), nullable=True),
    sa.Column('imap_port', sa.Integer(), nullable=False),
    sa.Column('imap_user', sa.String(), nullable=True),
    sa.Column('imap_app_password', sa.String(), nullable=True),
    sa.Column('imap_mailbox', sa.String(), nullable=False),
    sa.Column('smtp_host', sa.String(), nullable=True),
    sa.Column('smtp_port', sa.Integer(), nullable=False),
    sa.Column('smtp_user', sa.String(), nullable=True),
    sa.Column('smtp_password', sa.String(), nullable=True),
    sa.Column('steuer_email', sa.String(), nullable=True),
    sa.Column('paperless_email', sa.String(), nullable=True),
    sa.Column('girocode_email', sa.String(), nullable=True),
    sa.Column('default_forward_target', sa.String(), nullable=False),
    sa.Column('categories', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('board_columns',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('invoices') as batch_op:
        batch_op.add_column(sa.Column('payment_recipient_name', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('payment_iban', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('payment_bic', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('payment_reference', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('girocode_sent_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('board_column_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('board_position', sa.Integer(), nullable=False, server_default='0'))
        batch_op.create_foreign_key('fk_invoices_board_column_id', 'board_columns', ['board_column_id'], ['id'])
    # ### end Alembic commands ###

    # Seed-Spalte anlegen und bestehende Rechnungen dorthin einsortieren
    board_columns = sa.table(
        'board_columns', sa.column('id', sa.Integer), sa.column('name', sa.String), sa.column('position', sa.Integer)
    )
    invoices = sa.table('invoices', sa.column('id', sa.Integer), sa.column('board_column_id', sa.Integer))

    bind = op.get_bind()
    bind.execute(board_columns.insert().values(name='Eingang', position=0))
    default_column_id = bind.execute(sa.select(board_columns.c.id)).scalar_one()
    bind.execute(invoices.update().values(board_column_id=default_column_id))


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('invoices') as batch_op:
        batch_op.drop_constraint('fk_invoices_board_column_id', type_='foreignkey')
        batch_op.drop_column('board_position')
        batch_op.drop_column('board_column_id')
        batch_op.drop_column('girocode_sent_at')
        batch_op.drop_column('payment_reference')
        batch_op.drop_column('payment_bic')
        batch_op.drop_column('payment_iban')
        batch_op.drop_column('payment_recipient_name')
    op.drop_table('board_columns')
    op.drop_table('app_settings')
    # ### end Alembic commands ###
