"""initial invoices schema

Revision ID: 50370c6cad4b
Revises: 
Create Date: 2026-08-11 15:44:32.176797

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '50370c6cad4b'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('invoices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source_type', sa.String(), nullable=False),
    sa.Column('source_detail', sa.String(), nullable=True),
    sa.Column('email_from', sa.String(), nullable=True),
    sa.Column('file_path', sa.String(), nullable=False),
    sa.Column('file_original_name', sa.String(), nullable=True),
    sa.Column('file_mime_type', sa.String(), nullable=True),
    sa.Column('file_hash_sha256', sa.String(), nullable=False),
    sa.Column('sender_name', sa.String(), nullable=True),
    sa.Column('invoice_number', sa.String(), nullable=True),
    sa.Column('invoice_date', sa.Date(), nullable=True),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.Column('amount_gross', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('amount_net', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('vat_amount', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('vat_rate', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('currency', sa.String(), nullable=False),
    sa.Column('category', sa.String(), nullable=True),
    sa.Column('raw_extracted_text', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('forwarded_to', sa.String(), nullable=True),
    sa.Column('forwarded_at', sa.DateTime(), nullable=True),
    sa.Column('notes', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('file_hash_sha256')
    )
    op.create_table('sync_state',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('mailbox', sa.String(), nullable=False),
    sa.Column('last_uid', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('mailbox')
    )
    op.create_table('invoice_status_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('invoice_id', sa.Integer(), nullable=False),
    sa.Column('old_status', sa.String(), nullable=True),
    sa.Column('new_status', sa.String(), nullable=False),
    sa.Column('changed_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('note', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoices.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('invoice_status_history')
    op.drop_table('sync_state')
    op.drop_table('invoices')
    # ### end Alembic commands ###
