"""recurring ended flag

Revision ID: 71752aaf601f
Revises: 88a10781694b
Create Date: 2026-08-11 18:51:13.019345

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '71752aaf601f'
down_revision: Union[str, None] = '88a10781694b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('invoices') as batch_op:
        batch_op.add_column(sa.Column('recurring_ended', sa.Boolean(), nullable=False, server_default=sa.false()))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('invoices') as batch_op:
        batch_op.drop_column('recurring_ended')
    # ### end Alembic commands ###
