"""paid tracking and due date reminders

Revision ID: 7f4369abd06d
Revises: 1252833500ab
Create Date: 2026-08-11 17:01:36.873586

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '7f4369abd06d'
down_revision: Union[str, None] = '1252833500ab'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('app_settings') as batch_op:
        batch_op.add_column(sa.Column('reminder_email', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('reminder_days_before', sa.Integer(), nullable=False, server_default='3'))

    with op.batch_alter_table('invoices') as batch_op:
        batch_op.add_column(sa.Column('paid_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('due_reminder_sent_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('invoices') as batch_op:
        batch_op.drop_column('due_reminder_sent_at')
        batch_op.drop_column('paid_at')

    with op.batch_alter_table('app_settings') as batch_op:
        batch_op.drop_column('reminder_days_before')
        batch_op.drop_column('reminder_email')
    # ### end Alembic commands ###
