"""recurring invoices and imap failure tracking

Revision ID: 88a10781694b
Revises: 7f4369abd06d
Create Date: 2026-08-11 18:35:13.247194

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '88a10781694b'
down_revision: Union[str, None] = '7f4369abd06d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('app_settings') as batch_op:
        batch_op.add_column(sa.Column('imap_consecutive_failures', sa.Integer(), nullable=False, server_default='0'))
        batch_op.add_column(sa.Column('imap_failure_notified_at', sa.DateTime(), nullable=True))

    with op.batch_alter_table('invoices') as batch_op:
        batch_op.add_column(sa.Column('is_recurring', sa.Boolean(), nullable=False, server_default=sa.false()))
        batch_op.add_column(sa.Column('recurrence_interval_days', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('invoices') as batch_op:
        batch_op.drop_column('recurrence_interval_days')
        batch_op.drop_column('is_recurring')

    with op.batch_alter_table('app_settings') as batch_op:
        batch_op.drop_column('imap_failure_notified_at')
        batch_op.drop_column('imap_consecutive_failures')
    # ### end Alembic commands ###
